### PR TITLE
Add more crypto oids

### PR DESCRIPTION
**Pull request by kpp**
Add oids:

- OID_SIG_ECDSA_WITH_SHA512
- OID_EC_P256
- OID_SIG_ED448
- OID_NIST_EC_P384
- OID_NIST_EC_P521
- OID_NIST_HASH_SHA384
- OID_NIST_HASH_SHA512

Fix https://github.com/rusticata/oid-registry/issues/6

### CODE REVIEW

**Comment by kpp** [comment]
alg-rsa-pss-sha:

sha256:
v0: https://lapo.it/asn1js/#MDCgDTALBglghkgBZQMEAgGhGjAYBgkqhkiG9w0BAQgwCwYJYIZIAWUDBAIBogMCASA
v1: https://lapo.it/asn1js/#MDKgDTALBglghkgBZQMEAgGhHDAaBgkqhkiG9w0BAQgwDQYJYIZIAWUDBAIBBQCiAwIBIA
v2: https://lapo.it/asn1js/#MDKgDzANBglghkgBZQMEAgEFAKEaMBgGCSqGSIb3DQEBCDALBglghkgBZQMEAgGiAwIBIA
v3: https://lapo.it/asn1js/#MDSgDzANBglghkgBZQMEAgEFAKEcMBoGCSqGSIb3DQEBCDANBglghkgBZQMEAgEFAKIDAgEg

sha384:
v0: https://lapo.it/asn1js/#MDCgDTALBglghkgBZQMEAgKhGjAYBgkqhkiG9w0BAQgwCwYJYIZIAWUDBAICogMCATA
v1: https://lapo.it/asn1js/#MDKgDTALBglghkgBZQMEAgKhHDAaBgkqhkiG9w0BAQgwDQYJYIZIAWUDBAICBQCiAwIBMA
v2: https://lapo.it/asn1js/#MDKgDzANBglghkgBZQMEAgIFAKEaMBgGCSqGSIb3DQEBCDALBglghkgBZQMEAgKiAwIBMA
v3: https://lapo.it/asn1js/#MDSgDzANBglghkgBZQMEAgIFAKEcMBoGCSqGSIb3DQEBCDANBglghkgBZQMEAgIFAKIDAgEw

sha512:
v0: https://lapo.it/asn1js/#MDCgDTALBglghkgBZQMEAgOhGjAYBgkqhkiG9w0BAQgwCwYJYIZIAWUDBAIDogMCAUA
v1: https://lapo.it/asn1js/#MDKgDTALBglghkgBZQMEAgOhHDAaBgkqhkiG9w0BAQgwDQYJYIZIAWUDBAIDBQCiAwIBQA
v2: https://lapo.it/asn1js/#MDKgDzANBglghkgBZQMEAgMFAKEaMBgGCSqGSIb3DQEBCDALBglghkgBZQMEAgOiAwIBQA
v3: https://lapo.it/asn1js/#MDSgDzANBglghkgBZQMEAgMFAKEcMBoGCSqGSIb3DQEBCDANBglghkgBZQMEAgMFAKIDAgFA

**Comment by kpp** [comment]
Looks  like we don't have to keep different versions of alg-rsa-pss-sha oids, because they are equal.

**Comment by kpp** [comment]
TODO add:

- 1.2.840.10045.3.1.7 - prime256v1
- 1.3.132.0.34 - secp384r1
- 1.3.132.0.35 - secp521r1

**Comment by chifflier** [comment]
Applied, thanks!

**Pull request merged**
